// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoCRUD.Application.API.Context;

#nullable disable

namespace ProjetoCRUD.Application.API.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    [Migration("20230304041439_InitialTable")]
    partial class InitialTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoCRUD.Application.API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua Hermann Tribess",
                            Age = 17,
                            LastName = "Godri",
                            Name = "Pedro",
                            Phone = "47999998888",
                            Profession = "Programador"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rua Alberto Einstein",
                            Age = 33,
                            LastName = "Lisboa",
                            Name = "Ramon",
                            Phone = "47999997777",
                            Profession = "Programador"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rua Julio Michel",
                            Age = 7,
                            LastName = "Godri",
                            Name = "Luiz",
                            Phone = "47999996666",
                            Profession = "Sushi Man"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
